export const craftTypes: { id: string; name: string }[] = [
  { id: 'print', name: 'print' },
  { id: 'photograph', name: 'photograph' },
  { id: 'drawing', name: 'drawing' },
  { id: 'photomechanical print', name: 'photomechanical print' },
  { id: 'carte-de-visite', name: 'carte-de-visite' },
  { id: 'letter', name: 'letter' },
  { id: 'stereograph', name: 'stereograph' },
  { id: 'history medal', name: 'history medal' },
  { id: 'painting', name: 'painting' },
  { id: 'cabinet photograph', name: 'cabinet photograph' },
  { id: 'coin', name: 'coin' },
  { id: 'book', name: 'book' },
  { id: 'documentary photographs', name: 'documentary photographs' },
  { id: 'poster', name: 'poster' },
  { id: 'text sheet', name: 'text sheet' },
  { id: 'plate (dishes)', name: 'plate (dishes)' },
  { id: 'fragment', name: 'fragment' },
  { id: 'jeton', name: 'jeton' },
  { id: 'magazine', name: 'magazine' },
  { id: 'sculpture', name: 'sculpture' },
  { id: 'medal', name: 'medal' },
  { id: 'furniture', name: 'furniture' },
  { id: 'frame', name: 'frame' },
  { id: 'lid', name: 'lid' },
  { id: 'manuscript', name: 'manuscript' },
  {
    id: 'lantern slide (photographic)',
    name: 'lantern slide (photographic)',
  },
  { id: 'vase', name: 'vase' },
  { id: 'bowl', name: 'bowl' },
  { id: 'box', name: 'box' },
  { id: 'tile', name: 'tile' },
  { id: 'service (set)', name: 'service (set)' },
  { id: 'tissue stereograph', name: 'tissue stereograph' },
  { id: 'collage', name: 'collage' },
  { id: 'musical instrument', name: 'musical instrument' },
  { id: 'dish', name: 'dish' },
  { id: 'figure', name: 'figure' },
  { id: 'miniature', name: 'miniature' },
  { id: 'demonstration model', name: 'demonstration model' },
  { id: 'jewellery', name: 'jewellery' },
  { id: 'pot', name: 'pot' },
  { id: 'document', name: 'document' },
  { id: 'contact print', name: 'contact print' },
  { id: 'poem', name: 'poem' },
  { id: 'ribbon (material)', name: 'ribbon (material)' },
  { id: 'ship model', name: 'ship model' },
  { id: 'spoon', name: 'spoon' },
  { id: 'brooch', name: 'brooch' },
  { id: 'award medal', name: 'award medal' },
  { id: 'braid', name: 'braid' },
  { id: 'candlestick', name: 'candlestick' },
  { id: 'copy', name: 'copy' },
  { id: 'button', name: 'button' },
  { id: 'siege coin', name: 'siege coin' },
  { id: 'playing card', name: 'playing card' },
  { id: 'half model', name: 'half model' },
  { id: 'decorated paper', name: 'decorated paper' },
  { id: 'goblet', name: 'goblet' },
  { id: 'builder\u0027s model', name: 'builder\u0027s model' },
  { id: 'chandelier', name: 'chandelier' },
  { id: 'Oriental rug', name: 'Oriental rug' },
  { id: 'album', name: 'album' },
  { id: 'brocade paper', name: 'brocade paper' },
  { id: 'miniature (painting)', name: 'miniature (painting)' },
  { id: 'Ektachrome', name: 'Ektachrome' },
  { id: 'cup', name: 'cup' },
  { id: 'flintlock pistol', name: 'flintlock pistol' },
  { id: 'scrapbook', name: 'scrapbook' },
  { id: 'gameboard', name: 'gameboard' },
  { id: 'postage stamp', name: 'postage stamp' },
  { id: 'tureen', name: 'tureen' },
  { id: 'chest', name: 'chest' },
  { id: 'wind instrument', name: 'wind instrument' },
  { id: 'pipe', name: 'pipe' },
  { id: 'calendar', name: 'calendar' },
  { id: 'marbled paper', name: 'marbled paper' },
  { id: 'table', name: 'table' },
  { id: 'textile materials', name: 'textile materials' },
  { id: 'hat', name: 'hat' },
  { id: 'photomontage', name: 'photomontage' },
  { id: 'brochure', name: 'brochure' },
  { id: 'percussion instrument', name: 'percussion instrument' },
  { id: 'color slide', name: 'color slide' },
  { id: 'salt (condiment vessel)', name: 'salt (condiment vessel)' },
  { id: 'cloth', name: 'cloth' },
  { id: 'folder (container)', name: 'folder (container)' },
  { id: 'locket', name: 'locket' },
  { id: 'case', name: 'case' },
  { id: 'printed matter', name: 'printed matter' },
  { id: 'card game', name: 'card game' },
  { id: 'part', name: 'part' },
  { id: 'necklace', name: 'necklace' },
  { id: 'tea service', name: 'tea service' },
  { id: 'pedestal', name: 'pedestal' },
  { id: 'portfolio', name: 'portfolio' },
  { id: 'panel', name: 'panel' },
  { id: 'pendant (jewelry)', name: 'pendant (jewelry)' },
  { id: 'toy', name: 'toy' },
  { id: 'steel (alloy)', name: 'steel (alloy)' },
  { id: 'scarf', name: 'scarf' },
  { id: 'tile tableau', name: 'tile tableau' },
];
