export const materials: { id: string; name: string }[] = [
  { id: 'paper', name: 'paper' },
  { id: 'photographic support', name: 'photographic support' },
  { id: 'cardboard', name: 'cardboard' },
  { id: 'ink', name: 'ink' },
  { id: 'pencil', name: 'pencil' },
  { id: 'chalk', name: 'chalk' },
  { id: 'baryta paper', name: 'baryta paper' },
  { id: 'watercolor (paint)', name: 'watercolor (paint)' },
  { id: 'silver (metal)', name: 'silver (metal)' },
  { id: 'linen (material)', name: 'linen (material)' },
  { id: 'wood (plant material)', name: 'wood (plant material)' },
  { id: 'glass', name: 'glass' },
  { id: 'porcelain', name: 'porcelain' },
  { id: 'copper (metal)', name: 'copper (metal)' },
  { id: 'glaze', name: 'glaze' },
  { id: 'silk', name: 'silk' },
  { id: 'printing ink', name: 'printing ink' },
  { id: 'oil paint (paint)', name: 'oil paint (paint)' },
  { id: 'gold (metal)', name: 'gold (metal)' },
  { id: 'deck paint', name: 'deck paint' },
  { id: 'earthenware', name: 'earthenware' },
  { id: 'India ink (ink)', name: 'India ink (ink)' },
  { id: 'bronze (metal)', name: 'bronze (metal)' },
  { id: 'iron (metal)', name: 'iron (metal)' },
  { id: 'metal', name: 'metal' },
  { id: 'RC paper', name: 'RC paper' },
  { id: 'brass (alloy)', name: 'brass (alloy)' },
  { id: 'cotton (textile)', name: 'cotton (textile)' },
  { id: 'leather', name: 'leather' },
  { id: 'canvas', name: 'canvas' },
  { id: 'paint (coating)', name: 'paint (coating)' },
  {
    id: 'Japanese paper (handmade paper)',
    name: 'Japanese paper (handmade paper)',
  },
  { id: 'cobalt (mineral)', name: 'cobalt (mineral)' },
  { id: 'panel', name: 'panel' },
  { id: 'textile materials', name: 'textile materials' },
  { id: 'oak (wood)', name: 'oak (wood)' },
  { id: 'tin glaze', name: 'tin glaze' },
  { id: 'wool', name: 'wool' },
  { id: 'lead (metal)', name: 'lead (metal)' },
  { id: 'tin (metal)', name: 'tin (metal)' },
  {
    id: 'parchment (animal material)',
    name: 'parchment (animal material)',
  },
  { id: 'gouache (paint)', name: 'gouache (paint)' },
  { id: 'stoneware', name: 'stoneware' },
  { id: 'graphite (mineral)', name: 'graphite (mineral)' },
  { id: 'transparant paper', name: 'transparant paper' },
  { id: 'gilding (material)', name: 'gilding (material)' },
  { id: 'velvet (fabric weave)', name: 'velvet (fabric weave)' },
  { id: 'ivory', name: 'ivory' },
  { id: 'gold leaf', name: 'gold leaf' },
  { id: 'tracing paper', name: 'tracing paper' },
  { id: 'walnut (hardwood)', name: 'walnut (hardwood)' },
  { id: 'lacquer (coating)', name: 'lacquer (coating)' },
  { id: 'Japanese paper', name: 'Japanese paper' },
  { id: 'prepared paper', name: 'prepared paper' },
  { id: 'rope', name: 'rope' },
  { id: 'pipe clay', name: 'pipe clay' },
  { id: 'ebony (wood)', name: 'ebony (wood)' },
  {
    id: 'plastic (organic material)',
    name: 'plastic (organic material)',
  },
  { id: 'celluloid (cellulosic)', name: 'celluloid (cellulosic)' },
  { id: 'satin', name: 'satin' },
  { id: 'mother of pearl', name: 'mother of pearl' },
  { id: 'lead glaze', name: 'lead glaze' },
  {
    id: 'photographic film (photographic materials)',
    name: 'photographic film (photographic materials)',
  },
  { id: 'marble (rock)', name: 'marble (rock)' },
  { id: 'bone china (material)', name: 'bone china (material)' },
  { id: 'mahogany (wood)', name: 'mahogany (wood)' },
  { id: 'zinc', name: 'zinc' },
  { id: 'newsprint', name: 'newsprint' },
  {
    id: 'terracotta (clay material)',
    name: 'terracotta (clay material)',
  },
  { id: 'bone (material)', name: 'bone (material)' },
  { id: 'silver thread', name: 'silver thread' },
  { id: 'batiste', name: 'batiste' },
  { id: 'rosewood (wood)', name: 'rosewood (wood)' },
  { id: 'steel (alloy)', name: 'steel (alloy)' },
  { id: 'cloth', name: 'cloth' },
  { id: 'ball-point pens', name: 'ball-point pens' },
  { id: 'gypsum', name: 'gypsum' },
  { id: 'pine (wood)', name: 'pine (wood)' },
  { id: 'marbled paper', name: 'marbled paper' },
  { id: 'beech (wood)', name: 'beech (wood)' },
  { id: 'linden', name: 'linden' },
  { id: 'corrugated board', name: 'corrugated board' },
  { id: 'maple (wood)', name: 'maple (wood)' },
  { id: 'boxwood', name: 'boxwood' },
  { id: 'horn (animal material)', name: 'horn (animal material)' },
  { id: 'watercolor paper', name: 'watercolor paper' },
  { id: 'sandstone', name: 'sandstone' },
  { id: 'blotting paper', name: 'blotting paper' },
  { id: 'China paper', name: 'China paper' },
  { id: 'engobe', name: 'engobe' },
  { id: 'silver stain', name: 'silver stain' },
  { id: 'diamond (mineral)', name: 'diamond (mineral)' },
  { id: 'felt (textile)', name: 'felt (textile)' },
  { id: 'pressure-sensitive tape', name: 'pressure-sensitive tape' },
  { id: 'nickel (metal)', name: 'nickel (metal)' },
  { id: 'pearl', name: 'pearl' },
  { id: 'wax', name: 'wax' },
  { id: 'taffeta', name: 'taffeta' },
  { id: 'imitation leather', name: 'imitation leather' },
  { id: 'poster paint', name: 'poster paint' },
];
