export const places: { id: string; name: string }[] = [
  { id: 'Amsterdam', name: 'Amsterdam' },
  { id: 'Netherlands', name: 'Netherlands' },
  { id: 'Paris', name: 'Paris' },
  { id: 'The Hague', name: 'The Hague' },
  { id: 'France', name: 'France' },
  { id: 'Antwerp', name: 'Antwerp' },
  { id: 'Northern Netherlands', name: 'Northern Netherlands' },
  { id: 'Italy', name: 'Italy' },
  { id: 'London', name: 'London' },
  { id: 'Haarlem', name: 'Haarlem' },
  { id: 'Rome', name: 'Rome' },
  { id: 'Germany', name: 'Germany' },
  { id: 'Berlin', name: 'Berlin' },
  { id: 'Leiden', name: 'Leiden' },
  { id: 'Brussels', name: 'Brussels' },
  { id: 'Utrecht', name: 'Utrecht' },
  { id: 'Japan', name: 'Japan' },
  { id: 'Rotterdam', name: 'Rotterdam' },
  { id: 'Low Countries', name: 'Low Countries' },
  { id: 'China', name: 'China' },
  { id: 'Augsburg', name: 'Augsburg' },
  { id: 'England', name: 'England' },
  { id: 'Delft', name: 'Delft' },
  { id: 'Southern Netherlands', name: 'Southern Netherlands' },
  { id: 'Venice', name: 'Venice' },
  { id: 'unknown', name: 'unknown' },
  { id: 'Cologne', name: 'Cologne' },
  { id: 'Vienna', name: 'Vienna' },
  { id: 'Dordrecht', name: 'Dordrecht' },
  { id: 'Belgium', name: 'Belgium' },
  { id: 'Suriname', name: 'Suriname' },
  { id: 'Europe', name: 'Europe' },
  { id: 'New York (city)', name: 'New York (city)' },
  { id: 'Arnhem', name: 'Arnhem' },
  { id: 'United States of America', name: 'United States of America' },
  { id: 'Middelburg', name: 'Middelburg' },
  { id: 'Sumatra', name: 'Sumatra' },
  { id: 'Nijmegen', name: 'Nijmegen' },
  { id: 'Java', name: 'Java' },
  { id: 'Austria', name: 'Austria' },
  { id: 'Maastricht', name: 'Maastricht' },
  { id: 'Dutch East Indies, The', name: 'Dutch East Indies, The' },
  { id: 'Spain', name: 'Spain' },
  { id: 'Indonesia', name: 'Indonesia' },
  { id: 'Switzerland', name: 'Switzerland' },
  { id: 'Batavia', name: 'Batavia' },
  { id: 'Den Bosch', name: 'Den Bosch' },
  { id: 'Great Britain', name: 'Great Britain' },
  { id: 'Naples', name: 'Naples' },
  { id: 'Deventer', name: 'Deventer' },
  { id: 'Surabaya', name: 'Surabaya' },
  { id: 'Bruges', name: 'Bruges' },
  { id: 'United Kingdom', name: 'United Kingdom' },
  { id: 'Ghent', name: 'Ghent' },
  { id: 'Mechelen', name: 'Mechelen' },
  { id: 'Lyon', name: 'Lyon' },
  { id: 'Liège', name: 'Liège' },
  { id: 'Gouda', name: 'Gouda' },
  { id: 'Kyoto', name: 'Kyoto' },
  { id: 'Pompeii', name: 'Pompeii' },
  { id: 'Hoorn (North Holland)', name: 'Hoorn (North Holland)' },
  { id: 'Copenhagen (city)', name: 'Copenhagen (city)' },
  { id: 'Voorschoten', name: 'Voorschoten' },
  { id: 'Flushing', name: 'Flushing' },
  { id: 'Norway', name: 'Norway' },
  { id: 'Russia', name: 'Russia' },
  { id: 'Enkhuizen', name: 'Enkhuizen' },
  { id: 'New York', name: 'New York' },
  { id: 'Poland', name: 'Poland' },
  { id: 'Birmingham', name: 'Birmingham' },
  { id: 'Glasgow', name: 'Glasgow' },
  { id: 'Lille', name: 'Lille' },
  { id: 'Cleves', name: 'Cleves' },
  { id: 'Zwickau', name: 'Zwickau' },
  { id: 'Holland', name: 'Holland' },
  { id: 'Sri Lanka', name: 'Sri Lanka' },
  { id: 'Marseille', name: 'Marseille' },
  { id: 'Denmark', name: 'Denmark' },
  { id: 'Louvain', name: 'Louvain' },
  { id: 'Singapore', name: 'Singapore' },
  { id: 'Zeist', name: 'Zeist' },
  { id: 'Sevilla', name: 'Sevilla' },
  { id: 'Gelderland', name: 'Gelderland' },
];
