export const techniques: { id: string; name: string }[] = [
  { id: 'etching', name: 'etching' },
  { id: 'engraving', name: 'engraving' },
  { id: 'albumen print', name: 'albumen print' },
  { id: 'pen', name: 'pen' },
  { id: 'gelatin silver print', name: 'gelatin silver print' },
  { id: 'letterpress printing', name: 'letterpress printing' },
  { id: 'brush', name: 'brush' },
  { id: 'collotype', name: 'collotype' },
  { id: 'writing (processes)', name: 'writing (processes)' },
  { id: 'striking (metalworking)', name: 'striking (metalworking)' },
  { id: 'drypoint', name: 'drypoint' },
  { id: 'printing', name: 'printing' },
  { id: 'painting', name: 'painting' },
  { id: 'vitrification', name: 'vitrification' },
  { id: 'gilding', name: 'gilding' },
  { id: 'printing block', name: 'printing block' },
  { id: 'color woodcut', name: 'color woodcut' },
  { id: 'steel engraving', name: 'steel engraving' },
  { id: 'casting', name: 'casting' },
  { id: 'cutting', name: 'cutting' },
  { id: 'slide', name: 'slide' },
  { id: 'damask', name: 'damask' },
  { id: 'bobbin lace', name: 'bobbin lace' },
  { id: 'drawing', name: 'drawing' },
  { id: 'salted paper print', name: 'salted paper print' },
  { id: 'embroidering', name: 'embroidering' },
  { id: 'photolithography', name: 'photolithography' },
  { id: 'glassblowing', name: 'glassblowing' },
  { id: 'cyanotype', name: 'cyanotype' },
  { id: 'majolica', name: 'majolica' },
  {
    id: 'block printing (relief printing process)',
    name: 'block printing (relief printing process)',
  },
  { id: 'carbon print', name: 'carbon print' },
  { id: 'forging', name: 'forging' },
  { id: 'collage', name: 'collage' },
  { id: 'inkjet print', name: 'inkjet print' },
  {
    id: 'gelatin silver slide on glass',
    name: 'gelatin silver slide on glass',
  },
  { id: 'lacquering', name: 'lacquering' },
  { id: 'perforating', name: 'perforating' },
  { id: 'counterproof', name: 'counterproof' },
  { id: 'photochrom', name: 'photochrom' },
  { id: 'knitting', name: 'knitting' },
  { id: 'grinding', name: 'grinding' },
  { id: 'retroussage', name: 'retroussage' },
  { id: 'snipping', name: 'snipping' },
  { id: 'ferrotyping', name: 'ferrotyping' },
  { id: 'sewing', name: 'sewing' },
  { id: 'nishiki-e', name: 'nishiki-e' },
  { id: 'manuscript', name: 'manuscript' },
  { id: 'ambrotype', name: 'ambrotype' },
  { id: 'relief printing', name: 'relief printing' },
  { id: 'pencil', name: 'pencil' },
  { id: 'polishing', name: 'polishing' },
  { id: 'tapestry', name: 'tapestry' },
  { id: 'Valenciennes lace', name: 'Valenciennes lace' },
  { id: 'decorated paper', name: 'decorated paper' },
  { id: 'Mechlin (lace)', name: 'Mechlin (lace)' },
  { id: 'wet collodion negative', name: 'wet collodion negative' },
  { id: 'sawing', name: 'sawing' },
  { id: 'soldering', name: 'soldering' },
  { id: 'twill', name: 'twill' },
  { id: 'inlay (process)', name: 'inlay (process)' },
  { id: 'stapling', name: 'stapling' },
  { id: 'braiding', name: 'braiding' },
  { id: 'Lille lace', name: 'Lille lace' },
  { id: 'combed marbled paper', name: 'combed marbled paper' },
  { id: 'Alençon lace', name: 'Alençon lace' },
  { id: 'Binche lace', name: 'Binche lace' },
  { id: 'mixed lace', name: 'mixed lace' },
  { id: 'printed matter', name: 'printed matter' },
  { id: 'filigree', name: 'filigree' },
  { id: 'marbled paper', name: 'marbled paper' },
  { id: 'ball-point pens', name: 'ball-point pens' },
  { id: 'Woodburygravure', name: 'Woodburygravure' },
  { id: 'Brussels bobbin lace', name: 'Brussels bobbin lace' },
  { id: 'phantasy marbled paper', name: 'phantasy marbled paper' },
  { id: 'snail marbled paper', name: 'snail marbled paper' },
  { id: 'agate marbled paper', name: 'agate marbled paper' },
  { id: 'scoring', name: 'scoring' },
  { id: 'ink', name: 'ink' },
  { id: 'Brussels point de gaze', name: 'Brussels point de gaze' },
  { id: 'filing', name: 'filing' },
  { id: 'old Flemish lace', name: 'old Flemish lace' },
  { id: 'Cluny lace', name: 'Cluny lace' },
  { id: 'crocheting', name: 'crocheting' },
  { id: 'gluing', name: 'gluing' },
  { id: 'lampas (textile material)', name: 'lampas (textile material)' },
  { id: 'stone marbled paper', name: 'stone marbled paper' },
  { id: 'Brussels appliqué', name: 'Brussels appliqué' },
  { id: 'spanish marbled paper', name: 'spanish marbled paper' },
  { id: 'Venetian raised work', name: 'Venetian raised work' },
  { id: 'chintz', name: 'chintz' },
  { id: 'flat Venetian (needle point)', name: 'flat Venetian (needle point)' },
  { id: 'jacquard', name: 'jacquard' },
  { id: 'shell marbled paper', name: 'shell marbled paper' },
  { id: 'chalk', name: 'chalk' },
  { id: 'blow molding', name: 'blow molding' },
  { id: 'basting', name: 'basting' },
  { id: 'cocoa marbled paper', name: 'cocoa marbled paper' },
  { id: 'hammering', name: 'hammering' },
  { id: 'torchon lace', name: 'torchon lace' },
];
